import = ["/home/lurian/.config/alacritty/themes/themes/catppuccin.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "ComicCodeLigatures Nerd Font"
style = "Bold"

[font.italic]
family = "ComicCodeLigatures Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 0
y = 0
