-- NvChad base46 theme generated by pywal16 (dark)
--
-- Expects wal to be run with `--cols16 lighten`, which gives:
--   color0      -> background
--   color1-6    -> muted accents sampled from the source image
--   color7      -> mid grey   (bg lightened 55%)
--   color8      -> dim grey   (bg lightened 35%) - comments
--   color9-14   -> bright accents (color1-6 lightened 25% + saturated 40%)
--   color15     -> bright foreground (bg lightened 75%)
--
-- Degrades gracefully if colors 9-14 are duplicates of 1-6 (plain pywal),
-- since every syntax color still gets a lightness boost for contrast.

local M = {{}}

local colors = require("base46.colors")
local lighten = colors.change_hex_lightness
local saturate = colors.change_hex_saturation
local mix = colors.mix

-- Clamp a color into a lightness band (and enforce a minimum saturation)
-- so any source image yields readable, hue-distinct syntax colors.
local function vivid(hex, lo, hi, min_s)
  local h, s, l = colors.hex2hsl(hex)
  l = math.min(math.max(l, lo), hi)
  s = math.max(s, min_s or 0.30)
  return colors.hsl2hex(h, s, l)
end

-- Bright accents (syntax) -----------------------------------------------
local accent1 = vivid("{color9}", 0.62, 0.72)
local accent2 = vivid("{color10}", 0.62, 0.72)
local accent3 = vivid("{color11}", 0.62, 0.72)
local accent4 = vivid("{color12}", 0.62, 0.72)
local accent5 = vivid("{color13}", 0.62, 0.72)
local accent6 = vivid("{color14}", 0.62, 0.72)

-- Foregrounds ------------------------------------------------------------
local fg = vivid("{color15}", 0.78, 0.88, 0)
local fg_dim = "{color7}"
local comment = vivid("{color8}", 0.48, 0.58, 0.10)

-- ========================================================================
-- BASE_30: UI colors
-- ========================================================================
M.base_30 = {{
  white = fg,

  -- background ramp
  darker_black = lighten("{color0}", -3),
  black = "{color0}",
  black2 = lighten("{color0}", 4),
  one_bg = lighten("{color0}", 8),
  one_bg2 = lighten("{color0}", 13),
  one_bg3 = lighten("{color0}", 18),

  -- grey ramp (line numbers, borders, inactive text)
  grey = lighten("{color0}", 28),
  grey_fg = lighten("{color0}", 36),
  grey_fg2 = lighten("{color0}", 32),
  light_grey = comment,

  line = lighten("{color0}", 12),

  -- accents
  red = accent1,
  baby_pink = lighten(accent1, 6),
  pink = lighten(accent5, 6),

  green = accent2,
  vibrant_green = saturate(lighten(accent2, 6), 10),

  blue = accent4,
  nord_blue = lighten(accent4, 6),

  yellow = accent3,
  sun = lighten(accent3, 6),
  -- hue-shifted (-25% of the wheel) so numbers/constants get a hue
  -- that is distinct even on monochromatic source images
  orange = vivid(colors.change_hex_hue(accent3, -25), 0.62, 0.72, 0.40),

  purple = accent5,
  dark_purple = lighten(accent5, -8),

  teal = accent6,
  cyan = lighten(accent6, 6),

  -- UI elements
  statusline_bg = lighten("{color0}", 4),
  lightbg = lighten("{color0}", 12),
  pmenu_bg = accent4,
  folder_bg = accent4,
}}

-- ========================================================================
-- BASE_16: syntax (base16 spec)
-- ========================================================================
M.base_16 = {{
  -- backgrounds
  base00 = "{color0}",
  base01 = lighten("{color0}", 5),
  base02 = lighten("{color0}", 10),
  base03 = lighten("{color0}", 20),

  -- foregrounds
  base04 = fg_dim,
  base05 = fg,
  base06 = lighten(fg, 5),
  base07 = lighten(fg, 10),

  -- syntax
  base08 = mix(accent1, fg, 25), -- variables, tags
  base09 = M.base_30.orange, -- numbers, constants
  base0A = M.base_30.sun, -- types, classes
  base0B = accent2, -- strings
  base0C = M.base_30.cyan, -- escapes, regex
  base0D = M.base_30.nord_blue, -- functions
  base0E = M.base_30.pink, -- keywords
  base0F = M.base_30.dark_purple, -- delimiters, deprecated
}}

M.type = "dark"

-- ========================================================================
-- POLISH_HL: extra separation between token classes
-- ========================================================================
M.polish_hl = {{
  treesitter = {{
    ["@operator"] = {{ fg = M.base_30.cyan }},
    ["@punctuation.bracket"] = {{ fg = fg_dim }},
    ["@punctuation.delimiter"] = {{ fg = fg_dim }},

    ["@variable"] = {{ fg = M.base_16.base05 }},
    ["@variable.parameter"] = {{ fg = M.base_16.base08 }},
    ["@variable.member"] = {{ fg = M.base_30.teal }},
    ["@variable.builtin"] = {{ fg = M.base_30.baby_pink }},
    ["@property"] = {{ fg = M.base_30.teal }},

    ["@function"] = {{ fg = M.base_30.blue }},
    ["@function.call"] = {{ fg = M.base_30.blue }},
    ["@function.method.call"] = {{ fg = M.base_30.nord_blue }},
    ["@function.builtin"] = {{ fg = M.base_30.cyan }},
    ["@constructor"] = {{ fg = M.base_30.sun }},

    ["@constant"] = {{ fg = M.base_30.orange }},
    ["@constant.builtin"] = {{ fg = M.base_30.orange, bold = true }},
    ["@number"] = {{ fg = M.base_30.orange }},
    ["@boolean"] = {{ fg = M.base_30.orange }},

    ["@keyword"] = {{ fg = M.base_30.purple, italic = true }},
    ["@keyword.return"] = {{ fg = M.base_30.pink, italic = true }},
    ["@keyword.function"] = {{ fg = M.base_30.purple, italic = true }},

    ["@type"] = {{ fg = M.base_30.yellow }},
    ["@type.builtin"] = {{ fg = M.base_30.sun }},

    ["@string"] = {{ fg = M.base_30.green }},
    ["@string.escape"] = {{ fg = M.base_30.cyan }},

    ["@comment"] = {{ fg = comment, italic = true }},
  }},

  syntax = {{
    Comment = {{ fg = comment, italic = true }},
    Operator = {{ fg = M.base_30.cyan }},
    String = {{ fg = M.base_30.green }},
    Number = {{ fg = M.base_30.orange }},
    Keyword = {{ fg = M.base_30.purple, italic = true }},
    Function = {{ fg = M.base_30.blue }},
    Type = {{ fg = M.base_30.yellow }},
  }},

  defaults = {{
    Comment = {{ fg = comment, italic = true }},
    LineNr = {{ fg = M.base_30.grey_fg }},
    CursorLineNr = {{ fg = M.base_30.sun }},
  }},
}}

return M
