pragma Singleton
import QtQuick

/**
 * WAL-generated color palette for Quickshell.
 * This file is auto-generated by pywal - do not edit manually.
 * Run `wal -R` or set a new wallpaper to regenerate.
 */
QtObject {{
    // Primary colors from wallpaper
    readonly property color background: "{background}"
    readonly property color foreground: "{foreground}"
    readonly property color cursor: "{cursor}"
    
    // 16-color palette
    readonly property color color0: "{color0}"   // Black (background-like)
    readonly property color color1: "{color1}"   // Red
    readonly property color color2: "{color2}"   // Green
    readonly property color color3: "{color3}"   // Yellow
    readonly property color color4: "{color4}"   // Blue
    readonly property color color5: "{color5}"   // Magenta
    readonly property color color6: "{color6}"   // Cyan
    readonly property color color7: "{color7}"   // White (foreground-like)
    readonly property color color8: "{color8}"   // Bright black
    readonly property color color9: "{color9}"   // Bright red
    readonly property color color10: "{color10}" // Bright green
    readonly property color color11: "{color11}" // Bright yellow
    readonly property color color12: "{color12}" // Bright blue
    readonly property color color13: "{color13}" // Bright magenta
    readonly property color color14: "{color14}" // Bright cyan
    readonly property color color15: "{color15}" // Bright white
    
    // Semantic aliases for UI usage
    readonly property color bgPrimary: background
    readonly property color bgSecondary: color0
    readonly property color bgTertiary: color8
    readonly property color bgAccent: Qt.rgba(color4.r, color4.g, color4.b, 0.3)
    
    readonly property color textPrimary: foreground
    readonly property color textSecondary: color7
    readonly property color textMuted: color8
    readonly property color textAccent: color4
    
    readonly property color accent: color4
    readonly property color accentBright: color12
    readonly property color success: color2
    readonly property color warning: color3
    readonly property color error: color1
    readonly property color info: color6
    
    readonly property color border: Qt.rgba(foreground.r, foreground.g, foreground.b, 0.15)
    readonly property color borderAccent: Qt.rgba(color4.r, color4.g, color4.b, 0.4)
    
    // Message bubble colors
    readonly property color userBubble: Qt.rgba(color4.r, color4.g, color4.b, 0.25)
    readonly property color assistantBubble: Qt.rgba(color8.r, color8.g, color8.b, 0.4)
    readonly property color systemBubble: Qt.rgba(color3.r, color3.g, color3.b, 0.2)
    
    // Interactive states
    readonly property color hoverOverlay: Qt.rgba(foreground.r, foreground.g, foreground.b, 0.08)
    readonly property color pressedOverlay: Qt.rgba(foreground.r, foreground.g, foreground.b, 0.15)
    readonly property color focusRing: Qt.rgba(color4.r, color4.g, color4.b, 0.5)
}}
