# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@dqbd/tiktoken-1.0.7" = {
      name = "_at_dqbd_slash_tiktoken";
      packageName = "@dqbd/tiktoken";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dqbd/tiktoken/-/tiktoken-1.0.7.tgz";
        sha512 = "bhR5k5W+8GLzysjk8zTMVygQZsgvf7W1F0IlL4ZQ5ugjo5rCyiwGM5d8DYriXspytfu98tv59niang3/T+FoDw==";
      };
    };
  };
in {
  aicommits = nodeEnv.buildNodePackage {
    name = "aicommits";
    packageName = "aicommits";
    version = "1.11.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/aicommits/-/aicommits-1.11.0.tgz";
      sha512 = "YRy+M230yIuJ+j3YqXRAtAbmR2rJSzST5TbJASPXqaIh7kMN477DGQS1cwqwTJeBdMXKBJrWJAgVd//LkoA4Wg==";
    };
    dependencies = [
      sources."@dqbd/tiktoken-1.0.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Writes your git commit messages for you with AI";
      homepage = "https://github.com/Nutlope/aicommits#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
